// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.yahoo.arrow.pb;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBQualityOfServiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:arrow.PBQualityOfService)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
     */
    com.yahoo.arrow.pb.Common.PBQualityOfService.Level getLevel();

    /**
     * <code>optional bytes uuid = 2;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional bytes uuid = 2;</code>
     */
    com.google.protobuf.ByteString getUuid();
  }
  /**
   * Protobuf type {@code arrow.PBQualityOfService}
   */
  public static final class PBQualityOfService extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:arrow.PBQualityOfService)
      PBQualityOfServiceOrBuilder {
    // Use PBQualityOfService.newBuilder() to construct.
    private PBQualityOfService(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBQualityOfService(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBQualityOfService defaultInstance;
    public static PBQualityOfService getDefaultInstance() {
      return defaultInstance;
    }

    public PBQualityOfService getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBQualityOfService(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.yahoo.arrow.pb.Common.PBQualityOfService.Level value = com.yahoo.arrow.pb.Common.PBQualityOfService.Level.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                level_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uuid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.arrow.pb.Common.internal_static_arrow_PBQualityOfService_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.arrow.pb.Common.internal_static_arrow_PBQualityOfService_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.arrow.pb.Common.PBQualityOfService.class, com.yahoo.arrow.pb.Common.PBQualityOfService.Builder.class);
    }

    public static com.google.protobuf.Parser<PBQualityOfService> PARSER =
        new com.google.protobuf.AbstractParser<PBQualityOfService>() {
      public PBQualityOfService parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBQualityOfService(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBQualityOfService> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code arrow.PBQualityOfService.Level}
     */
    public enum Level
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AT_MOST_ONCE = 1;</code>
       */
      AT_MOST_ONCE(0, 1),
      /**
       * <code>AT_LEAST_ONCE = 2;</code>
       */
      AT_LEAST_ONCE(1, 2),
      /**
       * <code>EXACTLY_ONCE = 3;</code>
       */
      EXACTLY_ONCE(2, 3),
      ;

      /**
       * <code>AT_MOST_ONCE = 1;</code>
       */
      public static final int AT_MOST_ONCE_VALUE = 1;
      /**
       * <code>AT_LEAST_ONCE = 2;</code>
       */
      public static final int AT_LEAST_ONCE_VALUE = 2;
      /**
       * <code>EXACTLY_ONCE = 3;</code>
       */
      public static final int EXACTLY_ONCE_VALUE = 3;


      public final int getNumber() { return value; }

      public static Level valueOf(int value) {
        switch (value) {
          case 1: return AT_MOST_ONCE;
          case 2: return AT_LEAST_ONCE;
          case 3: return EXACTLY_ONCE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Level>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Level>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Level>() {
              public Level findValueByNumber(int number) {
                return Level.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yahoo.arrow.pb.Common.PBQualityOfService.getDescriptor().getEnumTypes().get(0);
      }

      private static final Level[] VALUES = values();

      public static Level valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Level(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:arrow.PBQualityOfService.Level)
    }

    private int bitField0_;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private com.yahoo.arrow.pb.Common.PBQualityOfService.Level level_;
    /**
     * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
     */
    public com.yahoo.arrow.pb.Common.PBQualityOfService.Level getLevel() {
      return level_;
    }

    public static final int UUID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString uuid_;
    /**
     * <code>optional bytes uuid = 2;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes uuid = 2;</code>
     */
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }

    private void initFields() {
      level_ = com.yahoo.arrow.pb.Common.PBQualityOfService.Level.AT_MOST_ONCE;
      uuid_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, level_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, uuid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, level_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, uuid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Common.PBQualityOfService parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.arrow.pb.Common.PBQualityOfService prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arrow.PBQualityOfService}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:arrow.PBQualityOfService)
        com.yahoo.arrow.pb.Common.PBQualityOfServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.arrow.pb.Common.internal_static_arrow_PBQualityOfService_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.arrow.pb.Common.internal_static_arrow_PBQualityOfService_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.arrow.pb.Common.PBQualityOfService.class, com.yahoo.arrow.pb.Common.PBQualityOfService.Builder.class);
      }

      // Construct using com.yahoo.arrow.pb.Common.PBQualityOfService.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = com.yahoo.arrow.pb.Common.PBQualityOfService.Level.AT_MOST_ONCE;
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.arrow.pb.Common.internal_static_arrow_PBQualityOfService_descriptor;
      }

      public com.yahoo.arrow.pb.Common.PBQualityOfService getDefaultInstanceForType() {
        return com.yahoo.arrow.pb.Common.PBQualityOfService.getDefaultInstance();
      }

      public com.yahoo.arrow.pb.Common.PBQualityOfService build() {
        com.yahoo.arrow.pb.Common.PBQualityOfService result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.arrow.pb.Common.PBQualityOfService buildPartial() {
        com.yahoo.arrow.pb.Common.PBQualityOfService result = new com.yahoo.arrow.pb.Common.PBQualityOfService(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.arrow.pb.Common.PBQualityOfService) {
          return mergeFrom((com.yahoo.arrow.pb.Common.PBQualityOfService)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.arrow.pb.Common.PBQualityOfService other) {
        if (other == com.yahoo.arrow.pb.Common.PBQualityOfService.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.arrow.pb.Common.PBQualityOfService parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.arrow.pb.Common.PBQualityOfService) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yahoo.arrow.pb.Common.PBQualityOfService.Level level_ = com.yahoo.arrow.pb.Common.PBQualityOfService.Level.AT_MOST_ONCE;
      /**
       * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
       */
      public com.yahoo.arrow.pb.Common.PBQualityOfService.Level getLevel() {
        return level_;
      }
      /**
       * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
       */
      public Builder setLevel(com.yahoo.arrow.pb.Common.PBQualityOfService.Level value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .arrow.PBQualityOfService.Level level = 1;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = com.yahoo.arrow.pb.Common.PBQualityOfService.Level.AT_MOST_ONCE;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uuid = 2;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes uuid = 2;</code>
       */
      public com.google.protobuf.ByteString getUuid() {
        return uuid_;
      }
      /**
       * <code>optional bytes uuid = 2;</code>
       */
      public Builder setUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uuid = 2;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arrow.PBQualityOfService)
    }

    static {
      defaultInstance = new PBQualityOfService(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arrow.PBQualityOfService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arrow_PBQualityOfService_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arrow_PBQualityOfService_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\005arrow\"\222\001\n\022PBQualityOfSer" +
      "vice\022.\n\005level\030\001 \001(\0162\037.arrow.PBQualityOfS" +
      "ervice.Level\022\014\n\004uuid\030\002 \001(\014\">\n\005Level\022\020\n\014A" +
      "T_MOST_ONCE\020\001\022\021\n\rAT_LEAST_ONCE\020\002\022\020\n\014EXAC" +
      "TLY_ONCE\020\003B\030\n\022com.yahoo.arrow.pbZ\002pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_arrow_PBQualityOfService_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_arrow_PBQualityOfService_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arrow_PBQualityOfService_descriptor,
        new java.lang.String[] { "Level", "Uuid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
