// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webrtc.proto

package com.yahoo.arrow.pb;

public final class Webrtc {
  private Webrtc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBWebRTCConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:arrow.PBWebRTCConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string stunURL = 1;</code>
     */
    boolean hasStunURL();
    /**
     * <code>optional string stunURL = 1;</code>
     */
    java.lang.String getStunURL();
    /**
     * <code>optional string stunURL = 1;</code>
     */
    com.google.protobuf.ByteString
        getStunURLBytes();

    /**
     * <code>optional string turnURL = 2;</code>
     */
    boolean hasTurnURL();
    /**
     * <code>optional string turnURL = 2;</code>
     */
    java.lang.String getTurnURL();
    /**
     * <code>optional string turnURL = 2;</code>
     */
    com.google.protobuf.ByteString
        getTurnURLBytes();

    /**
     * <code>optional string turnUsername = 3;</code>
     */
    boolean hasTurnUsername();
    /**
     * <code>optional string turnUsername = 3;</code>
     */
    java.lang.String getTurnUsername();
    /**
     * <code>optional string turnUsername = 3;</code>
     */
    com.google.protobuf.ByteString
        getTurnUsernameBytes();

    /**
     * <code>optional string turnCredential = 4;</code>
     */
    boolean hasTurnCredential();
    /**
     * <code>optional string turnCredential = 4;</code>
     */
    java.lang.String getTurnCredential();
    /**
     * <code>optional string turnCredential = 4;</code>
     */
    com.google.protobuf.ByteString
        getTurnCredentialBytes();
  }
  /**
   * Protobuf type {@code arrow.PBWebRTCConfig}
   */
  public static final class PBWebRTCConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:arrow.PBWebRTCConfig)
      PBWebRTCConfigOrBuilder {
    // Use PBWebRTCConfig.newBuilder() to construct.
    private PBWebRTCConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBWebRTCConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBWebRTCConfig defaultInstance;
    public static PBWebRTCConfig getDefaultInstance() {
      return defaultInstance;
    }

    public PBWebRTCConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBWebRTCConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              stunURL_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              turnURL_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              turnUsername_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              turnCredential_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<PBWebRTCConfig> PARSER =
        new com.google.protobuf.AbstractParser<PBWebRTCConfig>() {
      public PBWebRTCConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBWebRTCConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBWebRTCConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STUNURL_FIELD_NUMBER = 1;
    private java.lang.Object stunURL_;
    /**
     * <code>optional string stunURL = 1;</code>
     */
    public boolean hasStunURL() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string stunURL = 1;</code>
     */
    public java.lang.String getStunURL() {
      java.lang.Object ref = stunURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stunURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stunURL = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStunURLBytes() {
      java.lang.Object ref = stunURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stunURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TURNURL_FIELD_NUMBER = 2;
    private java.lang.Object turnURL_;
    /**
     * <code>optional string turnURL = 2;</code>
     */
    public boolean hasTurnURL() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string turnURL = 2;</code>
     */
    public java.lang.String getTurnURL() {
      java.lang.Object ref = turnURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          turnURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string turnURL = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTurnURLBytes() {
      java.lang.Object ref = turnURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        turnURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TURNUSERNAME_FIELD_NUMBER = 3;
    private java.lang.Object turnUsername_;
    /**
     * <code>optional string turnUsername = 3;</code>
     */
    public boolean hasTurnUsername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string turnUsername = 3;</code>
     */
    public java.lang.String getTurnUsername() {
      java.lang.Object ref = turnUsername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          turnUsername_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string turnUsername = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTurnUsernameBytes() {
      java.lang.Object ref = turnUsername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        turnUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TURNCREDENTIAL_FIELD_NUMBER = 4;
    private java.lang.Object turnCredential_;
    /**
     * <code>optional string turnCredential = 4;</code>
     */
    public boolean hasTurnCredential() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string turnCredential = 4;</code>
     */
    public java.lang.String getTurnCredential() {
      java.lang.Object ref = turnCredential_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          turnCredential_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string turnCredential = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTurnCredentialBytes() {
      java.lang.Object ref = turnCredential_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        turnCredential_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      stunURL_ = "";
      turnURL_ = "";
      turnUsername_ = "";
      turnCredential_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStunURLBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTurnURLBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTurnUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTurnCredentialBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStunURLBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTurnURLBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTurnUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTurnCredentialBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arrow.PBWebRTCConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:arrow.PBWebRTCConfig)
        com.yahoo.arrow.pb.Webrtc.PBWebRTCConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig.Builder.class);
      }

      // Construct using com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stunURL_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        turnURL_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        turnUsername_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        turnCredential_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCConfig_descriptor;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig getDefaultInstanceForType() {
        return com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig.getDefaultInstance();
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig build() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig buildPartial() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig result = new com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stunURL_ = stunURL_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.turnURL_ = turnURL_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.turnUsername_ = turnUsername_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.turnCredential_ = turnCredential_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig) {
          return mergeFrom((com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig other) {
        if (other == com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig.getDefaultInstance()) return this;
        if (other.hasStunURL()) {
          bitField0_ |= 0x00000001;
          stunURL_ = other.stunURL_;
          onChanged();
        }
        if (other.hasTurnURL()) {
          bitField0_ |= 0x00000002;
          turnURL_ = other.turnURL_;
          onChanged();
        }
        if (other.hasTurnUsername()) {
          bitField0_ |= 0x00000004;
          turnUsername_ = other.turnUsername_;
          onChanged();
        }
        if (other.hasTurnCredential()) {
          bitField0_ |= 0x00000008;
          turnCredential_ = other.turnCredential_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.arrow.pb.Webrtc.PBWebRTCConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stunURL_ = "";
      /**
       * <code>optional string stunURL = 1;</code>
       */
      public boolean hasStunURL() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string stunURL = 1;</code>
       */
      public java.lang.String getStunURL() {
        java.lang.Object ref = stunURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stunURL_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stunURL = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStunURLBytes() {
        java.lang.Object ref = stunURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stunURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stunURL = 1;</code>
       */
      public Builder setStunURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stunURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stunURL = 1;</code>
       */
      public Builder clearStunURL() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stunURL_ = getDefaultInstance().getStunURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stunURL = 1;</code>
       */
      public Builder setStunURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stunURL_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object turnURL_ = "";
      /**
       * <code>optional string turnURL = 2;</code>
       */
      public boolean hasTurnURL() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string turnURL = 2;</code>
       */
      public java.lang.String getTurnURL() {
        java.lang.Object ref = turnURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            turnURL_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string turnURL = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTurnURLBytes() {
        java.lang.Object ref = turnURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          turnURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string turnURL = 2;</code>
       */
      public Builder setTurnURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        turnURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string turnURL = 2;</code>
       */
      public Builder clearTurnURL() {
        bitField0_ = (bitField0_ & ~0x00000002);
        turnURL_ = getDefaultInstance().getTurnURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string turnURL = 2;</code>
       */
      public Builder setTurnURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        turnURL_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object turnUsername_ = "";
      /**
       * <code>optional string turnUsername = 3;</code>
       */
      public boolean hasTurnUsername() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string turnUsername = 3;</code>
       */
      public java.lang.String getTurnUsername() {
        java.lang.Object ref = turnUsername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            turnUsername_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string turnUsername = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTurnUsernameBytes() {
        java.lang.Object ref = turnUsername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          turnUsername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string turnUsername = 3;</code>
       */
      public Builder setTurnUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        turnUsername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string turnUsername = 3;</code>
       */
      public Builder clearTurnUsername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        turnUsername_ = getDefaultInstance().getTurnUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string turnUsername = 3;</code>
       */
      public Builder setTurnUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        turnUsername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object turnCredential_ = "";
      /**
       * <code>optional string turnCredential = 4;</code>
       */
      public boolean hasTurnCredential() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string turnCredential = 4;</code>
       */
      public java.lang.String getTurnCredential() {
        java.lang.Object ref = turnCredential_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            turnCredential_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string turnCredential = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTurnCredentialBytes() {
        java.lang.Object ref = turnCredential_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          turnCredential_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string turnCredential = 4;</code>
       */
      public Builder setTurnCredential(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        turnCredential_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string turnCredential = 4;</code>
       */
      public Builder clearTurnCredential() {
        bitField0_ = (bitField0_ & ~0x00000008);
        turnCredential_ = getDefaultInstance().getTurnCredential();
        onChanged();
        return this;
      }
      /**
       * <code>optional string turnCredential = 4;</code>
       */
      public Builder setTurnCredentialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        turnCredential_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arrow.PBWebRTCConfig)
    }

    static {
      defaultInstance = new PBWebRTCConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arrow.PBWebRTCConfig)
  }

  public interface PBWebRTCOfferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:arrow.PBWebRTCOffer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string sdp = 1;</code>
     */
    boolean hasSdp();
    /**
     * <code>optional string sdp = 1;</code>
     */
    java.lang.String getSdp();
    /**
     * <code>optional string sdp = 1;</code>
     */
    com.google.protobuf.ByteString
        getSdpBytes();
  }
  /**
   * Protobuf type {@code arrow.PBWebRTCOffer}
   */
  public static final class PBWebRTCOffer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:arrow.PBWebRTCOffer)
      PBWebRTCOfferOrBuilder {
    // Use PBWebRTCOffer.newBuilder() to construct.
    private PBWebRTCOffer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBWebRTCOffer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBWebRTCOffer defaultInstance;
    public static PBWebRTCOffer getDefaultInstance() {
      return defaultInstance;
    }

    public PBWebRTCOffer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBWebRTCOffer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sdp_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCOffer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCOffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer.Builder.class);
    }

    public static com.google.protobuf.Parser<PBWebRTCOffer> PARSER =
        new com.google.protobuf.AbstractParser<PBWebRTCOffer>() {
      public PBWebRTCOffer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBWebRTCOffer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBWebRTCOffer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SDP_FIELD_NUMBER = 1;
    private java.lang.Object sdp_;
    /**
     * <code>optional string sdp = 1;</code>
     */
    public boolean hasSdp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sdp = 1;</code>
     */
    public java.lang.String getSdp() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sdp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSdpBytes() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sdp_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSdpBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSdpBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arrow.PBWebRTCOffer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:arrow.PBWebRTCOffer)
        com.yahoo.arrow.pb.Webrtc.PBWebRTCOfferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCOffer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCOffer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer.Builder.class);
      }

      // Construct using com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sdp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCOffer_descriptor;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer getDefaultInstanceForType() {
        return com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer.getDefaultInstance();
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer build() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer buildPartial() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer result = new com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sdp_ = sdp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer) {
          return mergeFrom((com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer other) {
        if (other == com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer.getDefaultInstance()) return this;
        if (other.hasSdp()) {
          bitField0_ |= 0x00000001;
          sdp_ = other.sdp_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.arrow.pb.Webrtc.PBWebRTCOffer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sdp_ = "";
      /**
       * <code>optional string sdp = 1;</code>
       */
      public boolean hasSdp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public java.lang.String getSdp() {
        java.lang.Object ref = sdp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSdpBytes() {
        java.lang.Object ref = sdp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder setSdp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder clearSdp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sdp_ = getDefaultInstance().getSdp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder setSdpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdp_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arrow.PBWebRTCOffer)
    }

    static {
      defaultInstance = new PBWebRTCOffer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arrow.PBWebRTCOffer)
  }

  public interface PBWebRTCAnswerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:arrow.PBWebRTCAnswer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string sdp = 1;</code>
     */
    boolean hasSdp();
    /**
     * <code>optional string sdp = 1;</code>
     */
    java.lang.String getSdp();
    /**
     * <code>optional string sdp = 1;</code>
     */
    com.google.protobuf.ByteString
        getSdpBytes();
  }
  /**
   * Protobuf type {@code arrow.PBWebRTCAnswer}
   */
  public static final class PBWebRTCAnswer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:arrow.PBWebRTCAnswer)
      PBWebRTCAnswerOrBuilder {
    // Use PBWebRTCAnswer.newBuilder() to construct.
    private PBWebRTCAnswer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBWebRTCAnswer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBWebRTCAnswer defaultInstance;
    public static PBWebRTCAnswer getDefaultInstance() {
      return defaultInstance;
    }

    public PBWebRTCAnswer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBWebRTCAnswer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sdp_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCAnswer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCAnswer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer.Builder.class);
    }

    public static com.google.protobuf.Parser<PBWebRTCAnswer> PARSER =
        new com.google.protobuf.AbstractParser<PBWebRTCAnswer>() {
      public PBWebRTCAnswer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBWebRTCAnswer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBWebRTCAnswer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SDP_FIELD_NUMBER = 1;
    private java.lang.Object sdp_;
    /**
     * <code>optional string sdp = 1;</code>
     */
    public boolean hasSdp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sdp = 1;</code>
     */
    public java.lang.String getSdp() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sdp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSdpBytes() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sdp_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSdpBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSdpBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arrow.PBWebRTCAnswer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:arrow.PBWebRTCAnswer)
        com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCAnswer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCAnswer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer.Builder.class);
      }

      // Construct using com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sdp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCAnswer_descriptor;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer getDefaultInstanceForType() {
        return com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer.getDefaultInstance();
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer build() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer buildPartial() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer result = new com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sdp_ = sdp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer) {
          return mergeFrom((com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer other) {
        if (other == com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer.getDefaultInstance()) return this;
        if (other.hasSdp()) {
          bitField0_ |= 0x00000001;
          sdp_ = other.sdp_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.arrow.pb.Webrtc.PBWebRTCAnswer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sdp_ = "";
      /**
       * <code>optional string sdp = 1;</code>
       */
      public boolean hasSdp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public java.lang.String getSdp() {
        java.lang.Object ref = sdp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSdpBytes() {
        java.lang.Object ref = sdp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder setSdp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder clearSdp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sdp_ = getDefaultInstance().getSdp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder setSdpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdp_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arrow.PBWebRTCAnswer)
    }

    static {
      defaultInstance = new PBWebRTCAnswer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arrow.PBWebRTCAnswer)
  }

  public interface PBWebRTCCandidateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:arrow.PBWebRTCCandidate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string sdp = 1;</code>
     */
    boolean hasSdp();
    /**
     * <code>optional string sdp = 1;</code>
     */
    java.lang.String getSdp();
    /**
     * <code>optional string sdp = 1;</code>
     */
    com.google.protobuf.ByteString
        getSdpBytes();

    /**
     * <code>optional uint32 lineIndex = 2;</code>
     */
    boolean hasLineIndex();
    /**
     * <code>optional uint32 lineIndex = 2;</code>
     */
    int getLineIndex();

    /**
     * <code>optional string mid = 3;</code>
     */
    boolean hasMid();
    /**
     * <code>optional string mid = 3;</code>
     */
    java.lang.String getMid();
    /**
     * <code>optional string mid = 3;</code>
     */
    com.google.protobuf.ByteString
        getMidBytes();
  }
  /**
   * Protobuf type {@code arrow.PBWebRTCCandidate}
   */
  public static final class PBWebRTCCandidate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:arrow.PBWebRTCCandidate)
      PBWebRTCCandidateOrBuilder {
    // Use PBWebRTCCandidate.newBuilder() to construct.
    private PBWebRTCCandidate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBWebRTCCandidate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBWebRTCCandidate defaultInstance;
    public static PBWebRTCCandidate getDefaultInstance() {
      return defaultInstance;
    }

    public PBWebRTCCandidate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBWebRTCCandidate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sdp_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lineIndex_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              mid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCCandidate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCCandidate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate.Builder.class);
    }

    public static com.google.protobuf.Parser<PBWebRTCCandidate> PARSER =
        new com.google.protobuf.AbstractParser<PBWebRTCCandidate>() {
      public PBWebRTCCandidate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBWebRTCCandidate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBWebRTCCandidate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SDP_FIELD_NUMBER = 1;
    private java.lang.Object sdp_;
    /**
     * <code>optional string sdp = 1;</code>
     */
    public boolean hasSdp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sdp = 1;</code>
     */
    public java.lang.String getSdp() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sdp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSdpBytes() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINEINDEX_FIELD_NUMBER = 2;
    private int lineIndex_;
    /**
     * <code>optional uint32 lineIndex = 2;</code>
     */
    public boolean hasLineIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 lineIndex = 2;</code>
     */
    public int getLineIndex() {
      return lineIndex_;
    }

    public static final int MID_FIELD_NUMBER = 3;
    private java.lang.Object mid_;
    /**
     * <code>optional string mid = 3;</code>
     */
    public boolean hasMid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string mid = 3;</code>
     */
    public java.lang.String getMid() {
      java.lang.Object ref = mid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMidBytes() {
      java.lang.Object ref = mid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sdp_ = "";
      lineIndex_ = 0;
      mid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSdpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, lineIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMidBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSdpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, lineIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code arrow.PBWebRTCCandidate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:arrow.PBWebRTCCandidate)
        com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCCandidate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCCandidate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate.class, com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate.Builder.class);
      }

      // Construct using com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sdp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lineIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        mid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.arrow.pb.Webrtc.internal_static_arrow_PBWebRTCCandidate_descriptor;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate getDefaultInstanceForType() {
        return com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate.getDefaultInstance();
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate build() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate buildPartial() {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate result = new com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sdp_ = sdp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lineIndex_ = lineIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mid_ = mid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate) {
          return mergeFrom((com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate other) {
        if (other == com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate.getDefaultInstance()) return this;
        if (other.hasSdp()) {
          bitField0_ |= 0x00000001;
          sdp_ = other.sdp_;
          onChanged();
        }
        if (other.hasLineIndex()) {
          setLineIndex(other.getLineIndex());
        }
        if (other.hasMid()) {
          bitField0_ |= 0x00000004;
          mid_ = other.mid_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.arrow.pb.Webrtc.PBWebRTCCandidate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sdp_ = "";
      /**
       * <code>optional string sdp = 1;</code>
       */
      public boolean hasSdp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public java.lang.String getSdp() {
        java.lang.Object ref = sdp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSdpBytes() {
        java.lang.Object ref = sdp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder setSdp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder clearSdp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sdp_ = getDefaultInstance().getSdp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdp = 1;</code>
       */
      public Builder setSdpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdp_ = value;
        onChanged();
        return this;
      }

      private int lineIndex_ ;
      /**
       * <code>optional uint32 lineIndex = 2;</code>
       */
      public boolean hasLineIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 lineIndex = 2;</code>
       */
      public int getLineIndex() {
        return lineIndex_;
      }
      /**
       * <code>optional uint32 lineIndex = 2;</code>
       */
      public Builder setLineIndex(int value) {
        bitField0_ |= 0x00000002;
        lineIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 lineIndex = 2;</code>
       */
      public Builder clearLineIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lineIndex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mid_ = "";
      /**
       * <code>optional string mid = 3;</code>
       */
      public boolean hasMid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string mid = 3;</code>
       */
      public java.lang.String getMid() {
        java.lang.Object ref = mid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMidBytes() {
        java.lang.Object ref = mid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mid = 3;</code>
       */
      public Builder setMid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mid = 3;</code>
       */
      public Builder clearMid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mid_ = getDefaultInstance().getMid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mid = 3;</code>
       */
      public Builder setMidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mid_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:arrow.PBWebRTCCandidate)
    }

    static {
      defaultInstance = new PBWebRTCCandidate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:arrow.PBWebRTCCandidate)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arrow_PBWebRTCConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arrow_PBWebRTCConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arrow_PBWebRTCOffer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arrow_PBWebRTCOffer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arrow_PBWebRTCAnswer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arrow_PBWebRTCAnswer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arrow_PBWebRTCCandidate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arrow_PBWebRTCCandidate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014webrtc.proto\022\005arrow\"`\n\016PBWebRTCConfig\022" +
      "\017\n\007stunURL\030\001 \001(\t\022\017\n\007turnURL\030\002 \001(\t\022\024\n\014tur" +
      "nUsername\030\003 \001(\t\022\026\n\016turnCredential\030\004 \001(\t\"" +
      "\034\n\rPBWebRTCOffer\022\013\n\003sdp\030\001 \001(\t\"\035\n\016PBWebRT" +
      "CAnswer\022\013\n\003sdp\030\001 \001(\t\"@\n\021PBWebRTCCandidat" +
      "e\022\013\n\003sdp\030\001 \001(\t\022\021\n\tlineIndex\030\002 \001(\r\022\013\n\003mid" +
      "\030\003 \001(\tB\030\n\022com.yahoo.arrow.pbZ\002pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_arrow_PBWebRTCConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_arrow_PBWebRTCConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arrow_PBWebRTCConfig_descriptor,
        new java.lang.String[] { "StunURL", "TurnURL", "TurnUsername", "TurnCredential", });
    internal_static_arrow_PBWebRTCOffer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_arrow_PBWebRTCOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arrow_PBWebRTCOffer_descriptor,
        new java.lang.String[] { "Sdp", });
    internal_static_arrow_PBWebRTCAnswer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_arrow_PBWebRTCAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arrow_PBWebRTCAnswer_descriptor,
        new java.lang.String[] { "Sdp", });
    internal_static_arrow_PBWebRTCCandidate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_arrow_PBWebRTCCandidate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arrow_PBWebRTCCandidate_descriptor,
        new java.lang.String[] { "Sdp", "LineIndex", "Mid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
